stages:
  - prep
  - build
  - deploy

.vars-global:
  variables:
    CTRPF_REVISION : "unset"

prep:
  stage: prep
  extends:
    - .vars-global
  only:
    - develop
    - merge_requests
  script:
    - CTRPF_REVISION=`git describe --always --tags --match [0-9]* --abbrev=8 | sed 's/-[0-9]*-g/-/'`
    - echo "CTRPF_REVISION=$CTRPF_REVISION" >> build.env
    - cat build.env  
  artifacts:
    reports:
      dotenv: build.env
      
build:
  image: nanquitas/luma3ds:latest
  stage: build
  extends:
    - .vars-global
  only:
    - develop
    - merge_requests
  script:
    - echo $CTRPF_REVISION
    - cd Library && make dist-bin
    - cd ..
    - mv Library/libctrpf-$CTRPF_REVISION.tar.bz2 libctrpf-$CTRPF_REVISION.tar.bz2
  artifacts:
    paths:      
      - libctrpf-$CTRPF_REVISION.tar.bz2
    expire_in: 1 hour
  needs:
    - job: prep

deploy-hourly:
    image: inetprocess/gitlab-release
    stage: deploy
    extends:
    - .vars-global
    only:
        - develop
    script:
        - echo $CTRPF_REVISION
        - gitlab-release --message "hourly $CI_COMMIT_SHORT_SHA" libctrpf-$CTRPF_REVISION.tar.bz2
    needs:
      - job: prep
        artifacts: true
      - job: build
        artifacts: true
